### PR TITLE
Attempt to update for newer spec

### PR DESCRIPTION
**Pull request by justinfagnani**
I didn't quite know what to do with all the wildcard exports, which aren't supported, so I just removed them for now. With a little more work they could be marked as an interesting idea for the future instead. Don't know how you want to handle showing the post is updated either.

### CODE REVIEW

**Comment by notwaldorf** [comment]
This looks good! Thank you so much!!! I would leave the wildcard exports out for now -- they're in the git history if they ever make a comeback.

You could add a `<p><b>Updated May 18, 2020</b> with the updated syntax<p>` or something like that at the top to indicate this has been unfucked.

**Review by notwaldorf — APPROVED** [review]

**Comment by web-padawan** [comment]
> we don't have a shim that you can use in production. Hell, this shim isn't even guaranteed to work for all the cases that should work according to the spec,

@justinfagnani Shady Parts shim is currently in development, so maybe this could be rephrased as well, with a link to https://github.com/webcomponents/polyfills/issues/252. WDYT?

**Comment by justinfagnani** [comment]
@web-padawan I think I'll come back and add a reference when that's a bit more ready.

**Comment by notwaldorf** [comment]
Yasssss thanks j-man.

**Pull request merged**
